//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.27 at 11:50:33 PM GMT+10:00 
//


package iso.std.iso._20022.tech.xsd.pacs_002_001;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iso.std.iso._20022.tech.xsd.pacs_002_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.pacs_002_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link FIToFIPaymentStatusReportV09 }
     * 
     */
    public FIToFIPaymentStatusReportV09 createFIToFIPaymentStatusReportV09() {
        return new FIToFIPaymentStatusReportV09();
    }

    /**
     * Create an instance of {@link TaxInformation7 }
     * 
     */
    public TaxInformation7 createTaxInformation7() {
        return new TaxInformation7();
    }

    /**
     * Create an instance of {@link NumberOfTransactionsPerStatus5 }
     * 
     */
    public NumberOfTransactionsPerStatus5 createNumberOfTransactionsPerStatus5() {
        return new NumberOfTransactionsPerStatus5();
    }

    /**
     * Create an instance of {@link FrequencyAndMoment1 }
     * 
     */
    public FrequencyAndMoment1 createFrequencyAndMoment1() {
        return new FrequencyAndMoment1();
    }

    /**
     * Create an instance of {@link StatusReasonInformation11 }
     * 
     */
    public StatusReasonInformation11 createStatusReasonInformation11() {
        return new StatusReasonInformation11();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     * 
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link OriginalTransactionReference27 }
     * 
     */
    public OriginalTransactionReference27 createOriginalTransactionReference27() {
        return new OriginalTransactionReference27();
    }

    /**
     * Create an instance of {@link DocumentAdjustment1 }
     * 
     */
    public DocumentAdjustment1 createDocumentAdjustment1() {
        return new DocumentAdjustment1();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link TaxRecordDetails2 }
     * 
     */
    public TaxRecordDetails2 createTaxRecordDetails2() {
        return new TaxRecordDetails2();
    }

    /**
     * Create an instance of {@link GroupHeader53 }
     * 
     */
    public GroupHeader53 createGroupHeader53() {
        return new GroupHeader53();
    }

    /**
     * Create an instance of {@link DocumentLineInformation1 }
     * 
     */
    public DocumentLineInformation1 createDocumentLineInformation1() {
        return new DocumentLineInformation1();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link DateAndDateTime2Choice }
     * 
     */
    public DateAndDateTime2Choice createDateAndDateTime2Choice() {
        return new DateAndDateTime2Choice();
    }

    /**
     * Create an instance of {@link PaymentTransaction91 }
     * 
     */
    public PaymentTransaction91 createPaymentTransaction91() {
        return new PaymentTransaction91();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation15 }
     * 
     */
    public StructuredRemittanceInformation15 createStructuredRemittanceInformation15() {
        return new StructuredRemittanceInformation15();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link FrequencyPeriod1 }
     * 
     */
    public FrequencyPeriod1 createFrequencyPeriod1() {
        return new FrequencyPeriod1();
    }

    /**
     * Create an instance of {@link ReferredDocumentType3Choice }
     * 
     */
    public ReferredDocumentType3Choice createReferredDocumentType3Choice() {
        return new ReferredDocumentType3Choice();
    }

    /**
     * Create an instance of {@link TaxAmountAndType1 }
     * 
     */
    public TaxAmountAndType1 createTaxAmountAndType1() {
        return new TaxAmountAndType1();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     * 
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     * 
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation25 }
     * 
     */
    public PaymentTypeInformation25 createPaymentTypeInformation25() {
        return new PaymentTypeInformation25();
    }

    /**
     * Create an instance of {@link OrganisationIdentification8 }
     * 
     */
    public OrganisationIdentification8 createOrganisationIdentification8() {
        return new OrganisationIdentification8();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link RemittanceInformation15 }
     * 
     */
    public RemittanceInformation15 createRemittanceInformation15() {
        return new RemittanceInformation15();
    }

    /**
     * Create an instance of {@link GarnishmentType1Choice }
     * 
     */
    public GarnishmentType1Choice createGarnishmentType1Choice() {
        return new GarnishmentType1Choice();
    }

    /**
     * Create an instance of {@link EquivalentAmount2 }
     * 
     */
    public EquivalentAmount2 createEquivalentAmount2() {
        return new EquivalentAmount2();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     * 
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification5 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification5 createBranchAndFinancialInstitutionIdentification5() {
        return new BranchAndFinancialInstitutionIdentification5();
    }

    /**
     * Create an instance of {@link PersonIdentification13 }
     * 
     */
    public PersonIdentification13 createPersonIdentification13() {
        return new PersonIdentification13();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification3Choice }
     * 
     */
    public ClearingSystemIdentification3Choice createClearingSystemIdentification3Choice() {
        return new ClearingSystemIdentification3Choice();
    }

    /**
     * Create an instance of {@link SettlementInstruction4 }
     * 
     */
    public SettlementInstruction4 createSettlementInstruction4() {
        return new SettlementInstruction4();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice }
     * 
     */
    public AccountSchemeName1Choice createAccountSchemeName1Choice() {
        return new AccountSchemeName1Choice();
    }

    /**
     * Create an instance of {@link DocumentLineType1 }
     * 
     */
    public DocumentLineType1 createDocumentLineType1() {
        return new DocumentLineType1();
    }

    /**
     * Create an instance of {@link StatusReason6Choice }
     * 
     */
    public StatusReason6Choice createStatusReason6Choice() {
        return new StatusReason6Choice();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation7 }
     * 
     */
    public ReferredDocumentInformation7 createReferredDocumentInformation7() {
        return new ReferredDocumentInformation7();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link AmendmentInformationDetails12 }
     * 
     */
    public AmendmentInformationDetails12 createAmendmentInformationDetails12() {
        return new AmendmentInformationDetails12();
    }

    /**
     * Create an instance of {@link DiscountAmountAndType1 }
     * 
     */
    public DiscountAmountAndType1 createDiscountAmountAndType1() {
        return new DiscountAmountAndType1();
    }

    /**
     * Create an instance of {@link DocumentLineIdentification1 }
     * 
     */
    public DocumentLineIdentification1 createDocumentLineIdentification1() {
        return new DocumentLineIdentification1();
    }

    /**
     * Create an instance of {@link Charges2 }
     * 
     */
    public Charges2 createCharges2() {
        return new Charges2();
    }

    /**
     * Create an instance of {@link SupplementaryDataEnvelope1 }
     * 
     */
    public SupplementaryDataEnvelope1 createSupplementaryDataEnvelope1() {
        return new SupplementaryDataEnvelope1();
    }

    /**
     * Create an instance of {@link TaxAmountType1Choice }
     * 
     */
    public TaxAmountType1Choice createTaxAmountType1Choice() {
        return new TaxAmountType1Choice();
    }

    /**
     * Create an instance of {@link TaxAmount2 }
     * 
     */
    public TaxAmount2 createTaxAmount2() {
        return new TaxAmount2();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8 }
     * 
     */
    public FinancialInstitutionIdentification8 createFinancialInstitutionIdentification8() {
        return new FinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link MandateSetupReason1Choice }
     * 
     */
    public MandateSetupReason1Choice createMandateSetupReason1Choice() {
        return new MandateSetupReason1Choice();
    }

    /**
     * Create an instance of {@link CashAccount24 }
     * 
     */
    public CashAccount24 createCashAccount24() {
        return new CashAccount24();
    }

    /**
     * Create an instance of {@link TaxRecord2 }
     * 
     */
    public TaxRecord2 createTaxRecord2() {
        return new TaxRecord2();
    }

    /**
     * Create an instance of {@link Frequency36Choice }
     * 
     */
    public Frequency36Choice createFrequency36Choice() {
        return new Frequency36Choice();
    }

    /**
     * Create an instance of {@link DiscountAmountType1Choice }
     * 
     */
    public DiscountAmountType1Choice createDiscountAmountType1Choice() {
        return new DiscountAmountType1Choice();
    }

    /**
     * Create an instance of {@link MandateRelatedInformation12 }
     * 
     */
    public MandateRelatedInformation12 createMandateRelatedInformation12() {
        return new MandateRelatedInformation12();
    }

    /**
     * Create an instance of {@link ReferredDocumentType4 }
     * 
     */
    public ReferredDocumentType4 createReferredDocumentType4() {
        return new ReferredDocumentType4();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     * 
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link Party34Choice }
     * 
     */
    public Party34Choice createParty34Choice() {
        return new Party34Choice();
    }

    /**
     * Create an instance of {@link PartyIdentification125 }
     * 
     */
    public PartyIdentification125 createPartyIdentification125() {
        return new PartyIdentification125();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link TaxParty1 }
     * 
     */
    public TaxParty1 createTaxParty1() {
        return new TaxParty1();
    }

    /**
     * Create an instance of {@link TaxParty2 }
     * 
     */
    public TaxParty2 createTaxParty2() {
        return new TaxParty2();
    }

    /**
     * Create an instance of {@link SupplementaryData1 }
     * 
     */
    public SupplementaryData1 createSupplementaryData1() {
        return new SupplementaryData1();
    }

    /**
     * Create an instance of {@link GarnishmentType1 }
     * 
     */
    public GarnishmentType1 createGarnishmentType1() {
        return new GarnishmentType1();
    }

    /**
     * Create an instance of {@link DocumentLineType1Choice }
     * 
     */
    public DocumentLineType1Choice createDocumentLineType1Choice() {
        return new DocumentLineType1Choice();
    }

    /**
     * Create an instance of {@link PostalAddress6 }
     * 
     */
    public PostalAddress6 createPostalAddress6() {
        return new PostalAddress6();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice }
     * 
     */
    public ServiceLevel8Choice createServiceLevel8Choice() {
        return new ServiceLevel8Choice();
    }

    /**
     * Create an instance of {@link RemittanceAmount3 }
     * 
     */
    public RemittanceAmount3 createRemittanceAmount3() {
        return new RemittanceAmount3();
    }

    /**
     * Create an instance of {@link RemittanceAmount2 }
     * 
     */
    public RemittanceAmount2 createRemittanceAmount2() {
        return new RemittanceAmount2();
    }

    /**
     * Create an instance of {@link ContactDetails2 }
     * 
     */
    public ContactDetails2 createContactDetails2() {
        return new ContactDetails2();
    }

    /**
     * Create an instance of {@link OriginalGroupInformation29 }
     * 
     */
    public OriginalGroupInformation29 createOriginalGroupInformation29() {
        return new OriginalGroupInformation29();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link DatePeriod2 }
     * 
     */
    public DatePeriod2 createDatePeriod2() {
        return new DatePeriod2();
    }

    /**
     * Create an instance of {@link TaxAuthorisation1 }
     * 
     */
    public TaxAuthorisation1 createTaxAuthorisation1() {
        return new TaxAuthorisation1();
    }

    /**
     * Create an instance of {@link TaxPeriod2 }
     * 
     */
    public TaxPeriod2 createTaxPeriod2() {
        return new TaxPeriod2();
    }

    /**
     * Create an instance of {@link BranchData2 }
     * 
     */
    public BranchData2 createBranchData2() {
        return new BranchData2();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth1 }
     * 
     */
    public DateAndPlaceOfBirth1 createDateAndPlaceOfBirth1() {
        return new DateAndPlaceOfBirth1();
    }

    /**
     * Create an instance of {@link Party35Choice }
     * 
     */
    public Party35Choice createParty35Choice() {
        return new Party35Choice();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link AmountType4Choice }
     * 
     */
    public AmountType4Choice createAmountType4Choice() {
        return new AmountType4Choice();
    }

    /**
     * Create an instance of {@link Garnishment2 }
     * 
     */
    public Garnishment2 createGarnishment2() {
        return new Garnishment2();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     * 
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link OriginalGroupHeader13 }
     * 
     */
    public OriginalGroupHeader13 createOriginalGroupHeader13() {
        return new OriginalGroupHeader13();
    }

}
