use projectdb;

CREATE TABLE projectdb.TBL_PERSISTING_TRANS (MSG_ID varchar(100) NOT NULL,TRX_ID varchar(256) NOT NULL,CREDIT_DATE_TIME TIMESTAMP,BSB varchar(20),SUM_AMT float,BRANCH_ID varchar(40),STLMNT_AMT float,DEBTOR_NAME varchar(256),CREDITOR_NAME varchar(256),CURRENCY varchar(20), REQUEST_OBJ text NOT NULL, CREDITOR_ACC bigint NOT NULL, DEBTOR_ACC  bigint NOT NULL, PRIMARY KEY (MSG_ID));

